### ISSUE TITLE
ProjectWithBonds need 4 parameter for constructor

### ISSUE THREAD

**Issue by fjh1997** [alice-si/contracts#7]
in this demo,ProjectWithBonds constructor only receive 3 parameters,it will cause error.
app.js need to be fixed as below:
ProjectContract = await ProjectWithBonds.new(PROJECT_NAME, 10,100, 1000, {from: aliceAccount, gas: 5000000});

**Comment by jakub-wojciechowski** [comment]
Hi @fjh1997, 
Thank you so much for reporting this issue !!!
We've fixed in in PR: https://github.com/alice-si/contracts/pull/8

We'll appreciate, if you could post any other issues or questions here. 

BTW feel invited to our Slack: https://join.slack.com/t/alice-si/shared_invite/enQtMjE5NTAwNzQxMzMyLWM0YzI1MjA4YWNkYTU1YTE1Y2M4ODA1NGQzOWQ2ZjNiOTNhOTE2NGJlYjE4NTYzMmIxYTUxYzI5MTg0NGRmOTA

if you want to further discuss the code.
